name: dicoding_voiceapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.5.4 <=4.0.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/voiceapp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_bold.ttf
        - asset: assets/fonts/lato_regular.ttf
        # - asset: assets/fonts/lato_ligth.ttf
        - asset: assets/fonts/lato_thin.ttf
        - asset: assets/fonts/lato_italic.ttf
          style: italic
